#参照ruicky/jd_sign_bot

name: Github dkd-auto-coin
on:
    push:
        branches:
            - main
    schedule:
        - cron: '27 * * * *'
jobs:
    build:
        runs-on: ubuntu-latest
 
        steps:
            - name: Checkout codes
              uses: actions/checkout@v2
            - name: Use Node.js
              uses: actions/setup-node@v1
              with:
                node-version: '12.x'
            - name: Run
              run: npm install
            - run: node dkd_coin.js
              env:
                dkdurl: ${{ secrets.dkdurl }}
                dkdbody: ${{ secrets.dkdbody }}
                sckey: ${{ secrets.sckey }}
                dkdhd: ${{ secrets.dkdhd }}
            # 账号2
            - name: node dkd_coin_2
            
              env:
                dkdurl: ${{ secrets.dkdurl }}
                dkdbody: ${{ secrets.dkdbody2 }}
                sckey: ${{ secrets.sckey }}
                dkdhd: ${{ secrets.dkdhd2 }}
              run: node dkd_coin.js --dkdurl=${dkdurl} --dkdbody=${dkdbody} --dkdhd=${dkdhd} --tryrun
